# Generated by Django 4.0.1 on 2022-02-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_corta', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=50)),
                ('links', models.TextField()),
                ('salario_tiempo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(null=True, upload_to='imagenes')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes')),
                ('titulo', models.TextField()),
                ('empleos', models.TextField()),
                ('salarios', models.TextField()),
                ('resumen_calificaciones', models.TextField()),
                ('evaluaciones', models.TextField()),
                ('preguntas_respuestas', models.TextField()),
                ('informacion_entrevista', models.TextField()),
            ],
        ),
    ]
