# Generated by Django 4.0.1 on 2022-02-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appindeed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='evaluaciones',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='informacion_entrevista',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='preguntas_respuestas',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='resumen_calificaciones',
        ),
        migrations.AddField(
            model_name='empleo',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empleo',
            name='links',
            field=models.URLField(blank=True, null=True),
        ),
    ]
