# Generated by Django 4.0.1 on 2022-02-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appindeed', '0003_alter_empresa_banner_alter_empresa_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleo',
            name='descripcion_corta',
            field=models.CharField(max_length=300),
        ),
    ]
