# Generated by Django 4.0.1 on 2022-02-24 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appindeed', '0004_alter_empleo_descripcion_corta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='titulo',
            new_name='title_business',
        ),
    ]
