# Generated by Django 4.0.1 on 2022-02-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appindeed', '0005_rename_titulo_empresa_title_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='title_business',
            field=models.TextField(max_length=100),
        ),
    ]
