# Generated by Django 4.0.1 on 2022-02-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appindeed', '0006_alter_empresa_title_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='title_business',
            field=models.CharField(max_length=100),
        ),
    ]
