# Generated by Django 4.0.1 on 2022-03-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appindeed', '0007_alter_empresa_title_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100)),
                ('comentario', models.CharField(max_length=100)),
            ],
        ),
    ]
